### ISSUE TITLE
TypeError: destroy is not a function

### ISSUE THREAD

**Issue by theZulqarnain** [fareez-ahamed/react-datepicker#6]
When i have used DatePicker.tsx code getting this error.

`Unhandled Runtime Error
TypeError: destroy is not a function

Call Stack
commitHookEffectListUnmount
node_modules/react-dom/cjs/react-dom.development.js (19710:0)
commitPassiveHookEffects
node_modules/react-dom/cjs/react-dom.development.js (19768:0)
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js (188:0)
Object.invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js (237:0)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (292:0)
flushPassiveEffectsImpl
node_modules/react-dom/cjs/react-dom.development.js (22853:0)
unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js (653:0)
runWithPriority$1
node_modules/react-dom/cjs/react-dom.development.js (11039:0)
flushPassiveEffects
node_modules/react-dom/cjs/react-dom.development.js (22820:0)
performSyncWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (21737:0)
eval
node_modules/react-dom/cjs/react-dom.development.js (11089:0)
unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js (653:0)
runWithPriority$1
node_modules/react-dom/cjs/react-dom.development.js (11039:0)
flushSyncCallbackQueueImpl
node_modules/react-dom/cjs/react-dom.development.js (11084:0)
flushSyncCallbackQueue
node_modules/react-dom/cjs/react-dom.development.js (11072:0)
discreteUpdates$1
node_modules/react-dom/cjs/react-dom.development.js (21893:0)
discreteUpdates
node_modules/react-dom/cjs/react-dom.development.js (806:0)
dispatchDiscreteEvent
node_modules/react-dom/cjs/react-dom.development.js (4168:0)`

**Comment by fareez-ahamed** [comment]
Please provide more information. I'm not getting this error. Did you just clone this and ran and got error?
